### ISSUE TITLE
fail to start

### ISSUE THREAD

**Issue by kalle07** [tikendraw/reverse-image-search#1]
img_search 
what is that i have no file with that name ..

and 

g:\reverse-image-search>python launch.py
g:\reverse-image-search\v2\app.py
command: streamlit run g:\reverse-image-search\v2\app.py
The command “streamlit” is either misspelled or
could not be found.

g:\reverse-image-search>

only issue on install was 
ERROR: Package 'reverse-image-search' requires a different Python: 3.10.11 not in '<4.0,>=3.11'
but if rhat is the Error every-one should be create an environment

**Comment by tikendraw** [comment]
its  `image_search` and not `img_search`.

Sorry, i forgot to update the bash code in readme.

**Comment by kalle07** [comment]
i have noe file with a name
image_search


and still 

g:\reverse-image-search>python launch.py
g:\reverse-image-search\v2\app.py
command: streamlit run g:\reverse-image-search\v2\app.py
The command “streamlit” is either misspelled or
could not be found.

g:\reverse-image-search>

**Comment by tikendraw** [comment]
When you run pip install . , this registers a bash command  image_search which is same as running python launch. Py. ,  if image_search is not working, try python launch. Py

**Comment by tikendraw** [comment]
1 clone the repo

2  cd reverse-imag-search

3 pip install . 

4 python launch. Py

**Comment by tikendraw** [comment]
error - you have python3.10.11 installed, this reverse-image-search requires 3.11 or above. 

fix - i have update the requirement, now it supports python3.10 and above. 

step
- clone/pull again (to update the repo) 
- cd reverse-image-search
- pip install .
- python launch.py

**Comment by kalle07** [comment]
i see maybe its better for everyone to create an environment ?!?   ;)

**Comment by kalle07** [comment]
yes maybe ... , can you wtite the steps in readme, iv forgett  ;)


your new one is an error

Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb<0.6.0,>=0.5.12->reverse-image-search==0.1.3) (0.5.1)
Building wheels for collected packages: reverse-image-search
  Building wheel for reverse-image-search (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for reverse-image-search (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 124, in build
          self._copy_module(zip_file)
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 265, in _copy_module
          to_add = self.find_files_to_add()
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 171, in find_files_to_add
          for include in self._module.includes:
        File "C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.11\lib\functools.py", line 981, in __get__
          val = self.func(instance)
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 97, in _module
          return Module(
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\utils\module.py", line 75, in __init__
          PackageInclude(
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\utils\package_include.py", line 31, in __init__
          self.check_elements()
        File "C:\Users\kallemst\AppData\Local\Temp\pip-build-env-0qs3ahmv\overlay\Lib\site-packages\poetry\core\masonry\utils\package_include.py", line 72, in check_elements
          raise ValueError(
      ValueError: G:\reverse-image-search\reverse_image_search does not contain any element
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for reverse-image-search
Failed to build reverse-image-search
ERROR: Could not build wheels for reverse-image-search, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

g:\reverse-image-search>

**Comment by tikendraw** [comment]
follow this. 

```bash
#clone the latest repo
git clone https://github.com/tikendraw/reverse-image-search.git

# go inside
cd reverse-image-search

# create a virtual environment to avoid dependency confilct
python -m venv rev_venv

# activate the venv
source ./rev_venv/bin/activate

# install the dependencies
pip install . 

# run the app
python launch.py
```

if this doesn't work, just give up. 👍

**Comment by kalle07** [comment]
so long the installation without any error

but...
browser open and CMD shows


(rev_venv) g:\reverse-image-search>g:\reverse-image-search\rev_venv\Scripts\python.exe launch.py
g:\reverse-image-search\v2\app.py
command:  streamlit run g:\reverse-image-search\v2\app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.7.21:8501

2024-10-16 16:48:22.693 Uncaught app exception
Traceback (most recent call last):
  File "g:\reverse-image-search\rev_venv\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "g:\reverse-image-search\rev_venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "G:\reverse-image-search\v2\app.py", line 11, in <module>
    from embed_model import EfficientNetEmbeddingFunction
  File "g:\reverse-image-search\v2\embed_model.py", line 2, in <module>
    from transformers import AutoImageProcessor, AutoModel
ModuleNotFoundError: No module named 'transformers'


maybe better an environment with python 3.11 ???
i mean the next one get also an erroe ^^

**Comment by kalle07** [comment]
nop also error


(rev_venv) G:\reverse-image-search>pyenv versions
  3.10.11
  3.10.5
* 3.11.0b4 (set by C:\Users\kallemst\.pyenv\pyenv-win\version)
  3.7.4

(rev_venv) G:\reverse-image-search>g:\reverse-image-search\rev_venv\Scripts\python.exe launch.py
G:\reverse-image-search\v2\app.py
command:  streamlit run G:\reverse-image-search\v2\app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.7.21:8501

2024-10-16 17:21:28.332 Uncaught app exception
Traceback (most recent call last):
  File "G:\reverse-image-search\rev_venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "G:\reverse-image-search\rev_venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "G:\reverse-image-search\v2\app.py", line 11, in <module>
    from embed_model import EfficientNetEmbeddingFunction
  File "G:\reverse-image-search\v2\embed_model.py", line 2, in <module>
    from transformers import AutoImageProcessor, AutoModel
ModuleNotFoundError: No module named 'transformers'

**Comment by tikendraw** [comment]
Give up . This is not for you.  Go learn about pip and virtual environments.

**Comment by kalle07** [comment]
all is right 
i create a ot of it 
like oobadooga, a1111, 


will see how many have errors ^^

and i give you a lot of hints

**Comment by krabo0om** [comment]
@tikendraw thanks for creating the project, but kalle07's last error is actually a missing dependencies/requirement. I had to install the `transformers` package manually with pip.

**Comment by tikendraw** [comment]
Thanks, @krabo0om.
