### ISSUE TITLE
Cannot import img on windows

### ISSUE THREAD

**Issue by zoharli** [tikendraw/reverse-image-search#2]
Hello, i was trying to use it on windows, but whenever i import an image, it shows this import error:

Traceback (most recent call last):
  File "C:\Users\Zohar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\Zohar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "F:\image_manager\reverse-image-search\v2\app.py", line 158, in <module>
    main()
  File "F:\image_manager\reverse-image-search\v2\app.py", line 154, in main
    os.unlink(temp_file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Zohar\\AppData\\Local\\Temp\\tmpjwmoakp0.jpg'

**Comment by tikendraw** [comment]
try the new release v0.1.6. and tell me if it works. i do not have windows, i am just hoping this new release would fix it.
