### ISSUE TITLE
Crashes on malformed image

### ISSUE THREAD

**Issue by omgitsraven** [tikendraw/reverse-image-search#4]
I'm embedding a directory on Windows, and after running for a while, it suddenly hit this:

```
Adding images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.02it/s]
2024-12-18 09:16:58.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.███████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.02it/s]
2024-12-18 09:16:58.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Adding images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.92it/s]
2024-12-18 09:16:59.350 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.███████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.92it/s]
2024-12-18 09:16:59.350 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Adding images:   0%|                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
Creating Embeddings:   1%|▋                                                      | 179/14556 [03:04<4:07:08,  1.03s/it]                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Scripts\image_search_cli.exe\__main__.py", line 7, in <module>
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\cli.py", line 72, in create
    created_paths = create_embeddings(db, dir_path, recursive, config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\common.py", line 47, in create_embeddings
    db.add_images(batch_paths)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 212, in add_images
    self._add_images(
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 241, in _add_images
    embeddings = self.embed_images(batch_paths, batch_size=batch_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 198, in embed_images
    return self.embedding_model.batch_embed_images(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embed_model.py", line 64, in batch_embed_images
    processed_images = [self.load_image(image) for image in batch]
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embed_model.py", line 34, in load_image
    image = self.image_processor(images=image, return_tensors="pt").to(self.device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\image_processing_utils.py", line 41, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\utils\generic.py", line 852, in wrapper
    return func(*args, **valid_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\models\efficientnet\image_processing_efficientnet.py", line 318, in preprocess
    images = [to_numpy_array(image) for image in images]
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\image_utils.py", line 216, in to_numpy_array
    return np.array(img)
           ^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\PIL\Image.py", line 756, in __array_interface__
    new["data"] = self.tobytes()
                  ^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\PIL\Image.py", line 805, in tobytes
    self.load()
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\PIL\ImageFile.py", line 297, in load
    raise OSError(msg)
OSError: image file is truncated (19 bytes not processed)
```

In theory I'd just need to find and then delete the damaged file, but
1) it hasn't told me the filename, so I don't know which file is broken, and
2) it would be nice if it was able to catch the error and skip that file, rather than needing to restart the entire embed every time it hits a bad file

**Comment by omgitsraven** [comment]
Possibly related:  I just realised I left out the -r flag, and I was scanning a directory of *directories* of images, so in fact it seems like it must have choked on either a directory or a shortcut, rather than an image?

**Comment by tikendraw** [comment]
will do. 👍

**Comment by omgitsraven** [comment]
Thank you!  The logging now lets me deal with the file, although it might be worth mentioning, it still crashes, now in the exception handler instead?

```
Adding images: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.89it/s]
2024-12-19 08:39:19.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.89it/s]
2024-12-19 08:39:19.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Adding images: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.90it/s]
2024-12-19 08:39:20.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.90it/s]
2024-12-19 08:39:20.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Creating Embeddings:   1%|██▋                                                                                                                                                                                                                     | 179/14559 [03:16<2:35:47,  1.54it/s]ERROR:root:Error processing image <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=904x1280 at 0x21C203BE9F0>: image file is truncated (19 bytes not processed)                                                                                              | 0/1 [00:00<?, ?it/s]
WARNING:root:The following images failed to process : E:\Archive\testdata\badfile.jpg
Adding images:   0%|                                                                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]
Creating Embeddings:   1%|██▋                                                                                                                                                                                                                     | 179/14559 [03:16<4:23:40,  1.10s/it]
Traceback (most recent call last):
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\models\CollectionCommon.py", line 90, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\models\CollectionCommon.py", line 207, in _validate_and_prepare_add_request
    validate_insert_record_set(record_set=add_records)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\types.py", line 225, in validate_insert_record_set
    _validate_record_set_length_consistency(record_set)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\types.py", line 252, in _validate_record_set_length_consistency
    raise ValueError(f"Unequal lengths for fields: {error_str}")
ValueError: Unequal lengths for fields: ids: 16, embeddings: 15, uris: 16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Scripts\image_search_cli.exe\__main__.py", line 7, in <module>
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\cli.py", line 72, in create
    created_paths = create_embeddings(db, dir_path, recursive, config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\common.py", line 47, in create_embeddings
    db.add_images(batch_paths)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 212, in add_images
    self._add_images(
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 242, in _add_images
    self.collection.add(ids=batch_ids, uris=batch_paths, embeddings=embeddings)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\models\Collection.py", line 81, in add
    add_request = self._validate_and_prepare_add_request(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\models\CollectionCommon.py", line 93, in wrapper
    raise type(e)(msg).with_traceback(e.__traceback__)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\models\CollectionCommon.py", line 90, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\models\CollectionCommon.py", line 207, in _validate_and_prepare_add_request
    validate_insert_record_set(record_set=add_records)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\types.py", line 225, in validate_insert_record_set
    _validate_record_set_length_consistency(record_set)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\chromadb\api\types.py", line 252, in _validate_record_set_length_consistency
    raise ValueError(f"Unequal lengths for fields: {error_str}")
ValueError: Unequal lengths for fields: ids: 16, embeddings: 15, uris: 16 in add.
```

**Comment by tikendraw** [comment]
i hope latest pull will fix this problem now. i can't recreate the problem, that's why i cant test it.

**Comment by omgitsraven** [comment]
The error has changed to this:

```
Adding images: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.89it/s]
2024-12-20 10:13:06.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-20 10:13:06.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Adding images: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.78it/s]
2024-12-20 10:13:06.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-12-20 10:13:06.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Creating Embeddings:   1%|▋                                                      | 179/14561 [03:54<3:09:10,  1.27it/s]ERROR:root:Error processing image <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=904x1280 at 0x17001B96B70>: image file is truncated (19 bytes not processed)
ERROR:root:Failed processing the image: E:\Archive\testdata\badfile.jpg
Adding images:   0%|                                                                             | 0/1 [00:00<?, ?it/s]
Creating Embeddings:   1%|▋                                                      | 179/14561 [03:54<5:14:41,  1.31s/it]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Scripts\image_search_cli.exe\__main__.py", line 7, in <module>
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\cli.py", line 76, in create
    created_paths = create_embeddings(db, dir_path, recursive, config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\common.py", line 50, in create_embeddings
    db.add_images(batch_paths)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 220, in add_images
    self._add_images(
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 255, in _add_images
    batch_ids = [i for n,i in batch_ids if n not in bad_idx]
                       ^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by tikendraw** [comment]
do latest pull, above is not latest pull.

**Comment by omgitsraven** [comment]
So sorry, you're right -- I thought deleting the whole folder and doing a new git clone would've automatically fetched the latest, my mistake.    It successfully moves past the malformed files now, thank you so much!

**Comment by omgitsraven** [comment]
I've just hit a file that made it crash again, and this time it didn't even list the filename!

```
Adding images: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.20it/s]
2024-12-21 06:27:20.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.0:00<00:00,  2.20it/s]
2024-12-21 06:27:20.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Adding images: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.08it/s]
2024-12-21 06:27:23.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.0:00<00:00,  2.08it/s]
2024-12-21 06:27:23.877 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Creating Embeddings:  61%|███████████████████████████████                    | 14126/23187 [9:10:57<9:01:53,  3.59s/it]                            The channel dimension is ambiguous. Got image shape (1, 1, 3). Assuming channels are the first dimension.                     | 0/1 [00:00<?, ?it/s]
Adding images:   0%|                                                                                                         | 0/1 [00:00<?, ?it/s]
Creating Embeddings:  61%|███████████████████████████████                    | 14126/23187 [9:10:58<5:53:24,  2.34s/it]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Scripts\image_search_cli.exe\__main__.py", line 7, in <module>
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\cli.py", line 76, in create
    created_paths = create_embeddings(db, dir_path, recursive, config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\common.py", line 51, in create_embeddings
    db.add_images(batch_paths)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 227, in add_images
    self._add_images(
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 257, in _add_images
    embeddings, bad_images = self.embed_images(batch_paths, batch_size=batch_size)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embedding_store.py", line 213, in embed_images
    return self.embedding_model.batch_embed_images(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embed_model.py", line 75, in batch_embed_images
    processed_images = [self.load_image(image) for image in batch]
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\v2\embed_model.py", line 39, in load_image
    image = self.image_processor(images=image, return_tensors="pt").to(self.device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\image_processing_utils.py", line 41, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\utils\generic.py", line 852, in wrapper
    return func(*args, **valid_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\models\efficientnet\image_processing_efficientnet.py", line 351, in preprocess
    self.normalize(image=image, mean=image_mean, std=image_std, input_data_format=input_data_format)
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\image_processing_utils.py", line 111, in normalize
    return normalize(
           ^^^^^^^^^^
  File "C:\OtherPrograms\reverse-image-search\rev_venv\Lib\site-packages\transformers\image_transforms.py", line 398, in normalize
    raise ValueError(f"mean must have {num_channels} elements if it is an iterable, got {len(mean)}")
ValueError: mean must have 1 elements if it is an iterable, got 3
```

**Comment by tikendraw** [comment]
i wondering what kind of file is that which is breaking internals of transformers. this program just checks if it is jpg or png. it is not checking if file is corrupt or not. in such cases, this will result in error. I would suggest to scan your files for corruption. and remove them.

**Comment by kwwxis** [comment]
I'm getting that same error too:

![Image](https://github.com/user-attachments/assets/2b553a92-40b5-4ff6-b24f-6cd3872a32ca)

I've found out that it happens on non-corrupt images that have a height of 1px. Doesn't happen for 2px and widths of 1px seem to work okay.

I'm trying to see if I can use this to reverse search against datamined game asset images which is why I have 1px height images. I can just get rid of the 1px height images beforehand as workaround.

By the way, is there anyway you can stop the `Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode` messages when running in CLI?

**Comment by tikendraw** [comment]
> I'm getting that same error too:
> 
> ![Image](https://github.com/user-attachments/assets/2b553a92-40b5-4ff6-b24f-6cd3872a32ca)
> 
> I've found out that it happens on non-corrupt images that have a height of 1px. Doesn't happen for 2px and widths of 1px seem to work okay.
> 
> I'm trying to see if I can use this to reverse search against datamined game asset images which is why I have 1px height images. I can just get rid of the 1px height images beforehand as workaround.
> 
> By the way, is there anyway you can get rid of the `Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode` messages when running in CLI?

CNN requires pixels to perform multiplication with kernels; 1 px is simply not enough to perform the multiplication. That's why it is resulting in error. resizing 1X n pixel to input size (224x224) may work. I will try to filter images out based on their size to not cause this issue.

>By the way, is there anyway you can get rid of the Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode messages when running in CLI?

what commands are you using to run this?

**Comment by kwwxis** [comment]
> what commands are you using to run this?

Just using image_search_cli:
![Image](https://github.com/user-attachments/assets/06ff62f7-8133-4418-b245-398974a5d502)

The other guy, omgitsraven, was also getting them too:
![Image](https://github.com/user-attachments/assets/4de90fca-9cc2-4752-9f3d-b4c51d3cb4b6)

I get quite a lot of the messages when trying to run on Ubuntu as well:
![Image](https://github.com/user-attachments/assets/199aca40-39d2-4218-8d6c-74b7fcd1c306)

**Comment by tikendraw** [comment]
[v0.1.93](https://github.com/tikendraw/reverse-image-search/releases/tag/v0.1.93)  should resolve this issue, as it filters images before creating embeddings.
